1. What is a Python library? Why do we use Python libraries?
Ans:-A Python library is a collection of pre-written and reusable Python code that provides various functionalities to perform specific tasks. These libraries contain modules, functions, classes, and constants that enable developers to easily integrate certain features into their Python programs without having to write the code from scratch.

There are several reasons why we use Python libraries:

Efficiency: Python libraries save time and effort by providing pre-written code for common tasks. Instead of reinventing the wheel, developers can leverage existing libraries to quickly implement functionalities.

Functionality: Libraries extend the capabilities of Python by offering a wide range of functionalities for different purposes such as data manipulation, numerical computation, web development, machine learning, and more.

Reliability: Popular Python libraries are usually well-tested by a large community of developers, making them reliable and robust for various applications.

Consistency: Python libraries adhere to standard conventions and best practices, promoting code consistency and readability across different projects.

Community Support: Many Python libraries have active communities of developers who contribute to their improvement, provide support, and share knowledge through forums, documentation, and tutorials.

Interoperability: Python libraries can often work together seamlessly, allowing developers to combine functionalities from multiple libraries to solve complex problems efficiently.

2. What is the difference between Numpy array and List?
Ans:-NumPy arrays and Python lists are both data structures used to store collections of elements. However, they have several differences in terms of functionality, performance, and usage:

Performance: NumPy arrays are more efficient in terms of memory usage and computational speed compared to Python lists. NumPy arrays are implemented in C and optimized for performance, whereas Python lists are implemented in Python itself, which can lead to slower execution for certain operations.

Homogeneity: NumPy arrays are homogeneous, meaning all elements in the array must have the same data type. This allows for more efficient storage and computation, as NumPy can leverage fixed-size data types and optimized algorithms. On the other hand, Python lists can contain elements of different data types.

Vectorized operations: NumPy arrays support vectorized operations, which means that operations are applied element-wise without the need for explicit looping. This makes NumPy arrays particularly useful for numerical computations and mathematical operations. In contrast, Python lists require explicit looping for such operations, which can be less efficient.

Size: NumPy arrays are fixed in size, meaning the size of the array cannot be changed once it is created. In contrast, Python lists are dynamic and can grow or shrink in size as elements are added or removed.

Ease of use: Python lists are generally easier to work with for simple data structures and basic operations due to their flexibility and familiarity. NumPy arrays, while more powerful for numerical computing, may require some additional learning curve to fully utilize their capabilities.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [14]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# for finding shape
print("shape of the array is:",arr1.shape)

shape of the array is: (3, 4)


In [22]:
# for finding size
print("size of the array is:",arr1.size)

size of the array is: 12


In [23]:
# for dimention
print("dimention if the array is:",arr1.ndim)

dimention if the array is: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
# accessinf the first row of the array
arr2[0]

array([1, 2, 3, 4])

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [27]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# you access the element at the third row and fourth column
arr[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [30]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:,1::2]      

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [37]:
arr=np.random.rand(3,3)
arr

array([[0.06568892, 0.52876347, 0.0602326 ],
       [0.32666918, 0.93086993, 0.57363193],
       [0.59382349, 0.17419358, 0.3713533 ]])

8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand:- is for generate the random numbers from uniform distrubution over interval ([0,1])
np.random.randn:- is for generate the rabdom nummbers from normal distrubution (mean=0,standard devition=1)

9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [51]:
print("before expantion dimention :",arr.ndim)
arr2=np.expand_dims(arr,axis=0)
print("after expantion dimention:",arr2.ndim)

before expantion dimention : 2
after expantion dimention: 3


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [57]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# transpose of an array is 
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [72]:
Matrix_A=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print(Matrix_A)
print(Matrix_B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
# index wise multipliication
Matrix_A*Matrix_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
# Matrix multliplication
Matrix_A@Matrix_B

In [74]:
# Add both the matrix
Matrix_A+Matrix_B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [76]:
# Subtrct matrix B from A
Matrix_A-Matrix_B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [77]:
# Divide the matrix B from A
Matrix_A/Matrix_B

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
import numpy as np
arr=np.array([1,2,3,4],dtype=np.int32)
# swap byte order
arr_swapped=arr.byteswap()
print("original array:",arr)
print("Array with the swapped byte order:",arr_swapped)

original array: [1 2 3 4]
Array with the swapped byte order: [16777216 33554432 50331648 67108864]


In [ ]:
13. What is the significance of the np.linalg.inv function?

In [92]:
# The np.linalg.inv function in Numpy is used to compute the multliplication inverse of a matrix.
# In order words,it calculate the unverse of a sqaure matrix
# The significane of this function lies in various mathematics and computational application
# particularly in solving sytem of linear equation and linear algebra operation

import numpy as np
A=np.array([[2,3],[1,-2]])
B=np.array([8,-3])

# solve for variable x
x=np.linalg.inv(A).dot(B)
print(x)

[1. 2.]


In [103]:
# Reshape can use to change the shape of the data without any change of a data,it allows you to rearrange the elements of a new shape,provide the total number of elements remain same.
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
# Broadcasting is nothig but a when we are doing operations with an array then is appling to the ll thr elements in array is know as broadcasting
Z=np.zeros((3,3))
print("Before broadcasting")
print(Z)
A=Z+3
print("After broadcasting")
print(A)

Before broadcasting
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
After broadcasting
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
